### ISSUE TITLE
Problem playing certain PMD .M file by abruptly cutting off a certain FM channel

### ISSUE THREAD

**Issue by SilSinn9801** [autch/s98droid#1]
I am formally reporting here via GitHub a bug on this s98droid system that has bothered me (and still bothers me) since I started using the [Droidsound-E](https://github.com/droidmjt/Droidsound) app on my Android phone.

First things first, I start with a summary of the e-mail communication I had with @droidmjt since 2019-01-29:
> **SilSinn9801 to Droidmjt, Jan 29, 2019, 8:45 PM:**
There is a problem I discovered while testing a PMD98 track. For some reason, one of the FM channels abruptly cuts off in the middle of playback of each loop of such track and doesn't come back until the start of the next loop.
This problem so far happens only with this track in particular in Droidsound-E _(during this timeframe, I was using version 142)_ and not with other tracks, so I don't know if the issue here is with the track itself or with Droidsound-E itself (either some line of code that needs to be fixed, or some buffer setting that I might need to adjust myself). I also have to add that this never happened to me with PMDWin.dll under FMPMD2000.

> **SilSinn9801 to Droidmjt, Jan 30, 2019, 1:03 PM:**
To be specific, the problem happens with FM channel #3 whenever the M (M2, MZ, etc.) file, after playing a few notes on that channel, makes a change to that channel's TL registers without first specifying a new FM voice for that channel.
While PMDWin.dll and Hoot (Sound Hardware Emulator) assume that the same previous voice is reused (but with new TL values) when encountering such an instruction (corresponding to the "O#,±#" MML command where # are numbers), apparently Autch's PMDPlugin requires that such "O" instruction first expect the specification of a new voice ("@###" command in MML), otherwise falling back to a null ("000") voice (thus resulting in the silencing of FM#3 until the start of the next loop in my supplied file).
I tested the 2010 version of PMDWin.dll and the 2019 version of Hoot with my file and this channel-silencing issue does not happen there.

> _**(Droidmjt asked me to try version 143 on Jan 30, 2019, 4:13 PM)**_

> **SilSinn9801 to Droidmjt, Jan 30, 2019, 10:28 PM:**
I tested version 143 and still get the same problem with the same M file I sent you for testing: at approx. 2 minutes 17.5 seconds of playback, FM channel #3 goes blank until the next loop (when that channel changes voice) starts. And it happens only under Droidsound-E, not on Hoot or FMPMD2000.
Also, when I say FM channel #3, I am referring to the 3rd FM channel (when counting from 1 to 6), not the 4th FM channel (when counting from 0 to 5).
To make things simpler, I send you a ZIP containing: (1) a shorter, channel-isolated version of that same M file above (using only FM channels #1 and #3 and playing only the problematic part of the whole song), (2) its MML source (where you can see where the problem happens: channel C at the first "O14,-2" command), and (3) an AAC/M4A transcoding of the WAV file output by FMPMD2000 (from the same M file in this new ZIP) for comparison. This watered-down version still presents the problem I am talking about when playing on Droidsound-E, but not on FMPMD2000, except this time you don't need to wait until 2:17 to hear the problem. So maybe it's not a buffer problem.
_(attached file **[TH08_09P.ZIP](https://github.com/autch/s98droid/files/3205785/TH08_09P.ZIP)** to this email exchange; also uploaded to GitHub for your own examination since it is relevant to this issue)_

> **Droidmjt to SilSinn9801, Jan 31, 2019, 3:33 AM:**
Thanks for the files, I can try to investigate it but you should know that I have no real expertise on the pmdwin source, the best would be to contact the author (Autch) and ask him to investigate it if I cannot make this work. But let's see, maybe it is an easy fix.

> **Droidmjt to SilSinn9801, Jan 31, 2019, 5:17 PM:**
This is definitely decoder (pmdwin for android) related issue. There is nothing I can do, sorry.

Thus ended my communication with Droidmjt, and since back then I had no GitHub account, I proceeded to tweet Autch regarding this on 6:17 PM · Jan 31, 2019:
https://twitter.com/SinnerSilent/status/1091098074775199748
> @autch I have a problem with PMDSoundPlayer for Android <github.com/autch/s98droid>, sometimes silences FM channel C on M files that use O##,## command to adjust TL registers. Can you please take a look into this? Thankee!

Autch responded on 6:27 AM · Feb 3, 2019:
https://twitter.com/autch/status/1092006666285924352
> What platform plays correctly? s98droid uses PMDWin (c60.la.coocan.jp/download.html) codes to play PMD files, if you experience the same problem in other PMDWin-based pmd players, that's PMDWin's problem

I did not get to read his response until slightly more than a month later (because I did not have automatic notification by email enabled on my Twitter account. I replied back on 1:06 PM · Mar 7, 2019:
https://twitter.com/SinnerSilent/status/1103703525278842882
> Sorry for late reply (never got email notification). Windows (via FMPMD2000) plays my track correctly. The only problem so far is in Android.

As of today, that tweet has remained unanswered. Since then, Droidsound-E has been updated to version 150, and still I encounter the same issue when playing the same PMD file that otherwise plays just fine on the current versions of Hoot and FMPMD2000 (which makes use of PMDWin, also used by s98droid). @autch, can you please examine this issue with the M file contained in the ZIP file I attached to this bug report? Droidmjt already studied this issue and concluded it is a decoder plugin problem and not an app problem; maybe you can work this out directly with him since both of you are GitHub users.

_**Thankee!**_

**SilSinn9801** a.k.a. _**Silent Sinner in Scarlet**_

**Comment by autch** [comment]
Thank you for detailed investigation, I've reproduced the issue.
S98Player uses modified PMDWin codes, so problem may live in there.

certainly there is suspicious modification applied in PMDWin::tl_set(), https://github.com/autch/s98droid/blob/dcdcb31400b7f65491a8b631ac9bad18d160454c/jni/pmdwin/pmdwin.cpp#L4671
however changing them does not fix the problem...

**Comment by ghost** [comment]
Hello autch, I've been also investigating this problem but no luck yet. Today I learned that this: https://github.com/pbarfuss/PMDWinS036 seems to have the problem fixed. However the code there seems heavily modified compared to pmdwin in s98droid. Do you think the problem is inside the pmdwin.cpp or in fmgen?

**Comment by ghost** [comment]
I also downloaded the original PMDWIN src (http://c60.la.coocan.jp/download/PMDWinS036.lzh) and used the same fmgen as in s98droid, I got identical results when recorded the pcm data (the same problem appeared).  I wonder if the FMPMD2000 uses the same PMDWIN source.

**Comment by ghost** [comment]
change this: `dl = *si++;` to this: `dl = *(char*)si++;` solves the problem in the PMDWIN::tl_set function

**Comment by SilSinn9801** [comment]
Thankee to you all, this issue is solved. Closing it if you don’t mind.
